export const Categories = [
  {
    id: '1',
    name: 'Bulldozers',
    properties: [
      {
        id: '1',
        field: 'TextField',
        fieldName: 'Model',
        value: 'XXX-XXX',
        placeholder: 'Model of Machine',
      },
      {
        id: '2',
        field: 'DateField',
        fieldName: 'Manufactured On',
        value: '10/10/2023',
        placeholder: 'Date',
      },
      {
        id: '3',
        field: 'CheckboxField',
        fieldName: 'How does it works?',
        value: true,
        placeholder: 'How does it works?',
      },
      {
        id: '4',
        field: 'NumerField',
        fieldName: 'Weight',
        value: 7,
        placeholder: 'weight in tons',
      },
    ],
    items: [
      {
        id: '1',
        field: 'TextField',
        fieldName: 'Model',
        value: 'XXX-XXX',
        placeholder: 'Model of Machine',
      },
      {
        id: '2',
        field: 'DateField',
        fieldName: 'Manufactured On',
        value: '10/10/2023',
        placeholder: 'Date',
      },
      {
        id: '3',
        field: 'CheckboxField',
        fieldName: 'How does it works?',
        value: true,
        placeholder: 'How does it works?',
      },
      {
        id: '4',
        field: 'NumerField',
        fieldName: 'Weight',
        value: 7,
        placeholder: 'weight in tons',
      },
    ],
  },
  {
    id: '2',
    name: 'Creanes',
    properties: [
      {
        id: '1',
        field: 'TextField',
        fieldName: 'Model',
        value: 'XXX-XXX',
        placeholder: 'Model of Machine',
      },
      {
        id: '2',
        field: 'DateField',
        fieldName: 'Manufactured On',
        value: '10/10/2023',
        placeholder: 'Date',
      },
      {
        id: '3',
        field: 'CheckboxField',
        fieldName: 'How does it works?',
        value: true,
        placeholder: 'How does it works?',
      },
      {
        id: '4',
        field: 'NumerField',
        fieldName: 'Weight',
        value: 7,
        placeholder: 'weight in tons',
      },
    ],
    items: [
      {
        id: '1',
        field: 'TextField',
        fieldName: 'Model',
        value: 'XXX-XXX',
        placeholder: 'Model of Machine',
      },
      {
        id: '2',
        field: 'DateField',
        fieldName: 'Manufactured On',
        value: '10/10/2023',
        placeholder: 'Date',
      },
      {
        id: '3',
        field: 'CheckboxField',
        fieldName: 'How does it works?',
        value: true,
        placeholder: 'How does it works?',
      },
      {
        id: '4',
        field: 'NumerField',
        fieldName: 'Weight',
        value: 7,
        placeholder: 'weight in tons',
      },
    ],
  },
  {
    id: '3',
    name: 'Road Rollers',
    properties: [
      {
        id: '1',
        field: 'TextField',
        fieldName: 'Model',
        value: 'XXX-XXX',
        placeholder: 'Model of Machine',
      },
      {
        id: '2',
        field: 'DateField',
        fieldName: 'Manufactured On',
        value: '10/10/2023',
        placeholder: 'Date',
      },
      {
        id: '3',
        field: 'CheckboxField',
        fieldName: 'How does it works?',
        value: true,
        placeholder: 'How does it works?',
      },
      {
        id: '4',
        field: 'NumerField',
        fieldName: 'Weight',
        value: 7,
        placeholder: 'weight in tons',
      },
    ],
    items: [
      {
        id: '1',
        field: 'TextField',
        fieldName: 'Model',
        value: 'XXX-XXX',
        placeholder: 'Model of Machine',
      },
      {
        id: '2',
        field: 'DateField',
        fieldName: 'Manufactured On',
        value: '10/10/2023',
        placeholder: 'Date',
      },
      {
        id: '3',
        field: 'CheckboxField',
        fieldName: 'How does it works?',
        value: true,
        placeholder: 'How does it works?',
      },
      {
        id: '4',
        field: 'NumerField',
        fieldName: 'Weight',
        value: 7,
        placeholder: 'weight in tons',
      },
    ],
  },
  {
    id: '4',
    name: 'Concrete Mixer',
    properties: [
      {
        id: '1',
        field: 'TextField',
        fieldName: 'Model',
        value: 'XXX-XXX',
        placeholder: 'Model of Machine',
      },
      {
        id: '2',
        field: 'DateField',
        fieldName: 'Manufactured On',
        value: '10/10/2023',
        placeholder: 'Date',
      },
      {
        id: '3',
        field: 'CheckboxField',
        fieldName: 'How does it works?',
        value: true,
        placeholder: 'How does it works?',
      },
      {
        id: '4',
        field: 'NumerField',
        fieldName: 'Weight',
        value: 7,
        placeholder: 'weight in tons',
      },
    ],
    items: [
      {
        id: '1',
        field: 'TextField',
        fieldName: 'Model',
        value: 'XXX-XXX',
        placeholder: 'Model of Machine',
      },
      {
        id: '2',
        field: 'DateField',
        fieldName: 'Manufactured On',
        value: '10/10/2023',
        placeholder: 'Date',
      },
      {
        id: '3',
        field: 'CheckboxField',
        fieldName: 'How does it works?',
        value: true,
        placeholder: 'How does it works?',
      },
      {
        id: '4',
        field: 'NumerField',
        fieldName: 'Weight',
        value: 7,
        placeholder: 'weight in tons',
      },
    ],
  },
];

export const Properties = [
  {
    id: '1',
    field: 'TextField',
    fieldName: 'Model',
    value: 'XXX-XXX',
    placeholder: 'Model of Machine',
  },
  {
    id: '2',
    field: 'DateField',
    fieldName: 'Manufactured On',
    value: '10/10/2023',
    placeholder: 'Date',
  },
  {
    id: '3',
    field: 'CheckboxField',
    fieldName: 'How does it works?',
    value: true,
    placeholder: 'How does it works?',
  },
  {
    id: '4',
    field: 'NumerField',
    fieldName: 'Weight',
    value: 7,
    placeholder: 'weight in tons',
  },
];
